# Generated by Django 3.2.16 on 2022-12-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_author_reviews_recipe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='recipe_name',
            new_name='author',
        ),
    ]
